v1.5.0
_Note: Includes fixes from 1.4.0-beta.1 (never released to production),
1.5.0-beta.1, and one additional pull request (#2072)_

Update electron to 1.7.12 (#2029)

New design for import and install flows (#2053)

Support for 'light' imports, which bring just messages, contacts and
groups (#2053, #2072)

Set conversation disappearing messages state and contact block state on
initial link (#1980)

'Restart' -> 'Restart Signal' button in update dialog, thanks @StevenXL
(#2024)

Fixed: If app started offline, conversations would not open (#2064)

Fixed: Attached images would sometimes show up rotated improperly (#2040)

Fixed: Uncaught Exception: TypeError; 'getSize' (#2061)

Fixed: File paths with special characters could be shown in misleading
way

Fixed: incoming messages sometimes didn't appear at all (#2050)

Fixed: 'Cannot find module ./app/locale' error popup when attempting to
start another instance of the app on Windows (#2017)

Fixed: Setting NODE_ENV environment variable to 'development' would
point it at staging servers (#2010)

Dev:
  - Move ESLint environment configuration into `.eslintrc` (#2051)
  - Sync Protocol Buffers with `libsignal-service-java` (#2046)
  - Update to libsignal-protocol-javascript v1.3.0 (#2050)
  - Make our binary comparisons constant time (#2047)
  - Fix typo in issue template (#2020)
  - Update to new signal branding (#2018)